# Theme configuration
#
# Copyright © 2017 Vincent Besançon <besancon.vincent@gmail.com>
#                  Windsurf Attitude <https://windsurf-attitude.com>
# See LICENSE.
#
parent: classic
name: windsurf-attitude
display_name: Windsurf Attitude
version: 0.2.1
author:
  name: "Vincent BESANCON"
  email: "besancon.vincent@gmail.com"

assets:
  use_parent_assets: true
  css:
    all:
      - id: custom-style
        path: assets/css/custom.css
        media: all
        priority: 100
      - id: fixed-header-style
        path: assets/css/stickyheader.css
        media: all
        priority: 100

  js:
    all:
      - id: fixed-header-script
        path: assets/js/stickyheader.js
        priority: 100
        position: bottom

# global_settings:
#   hooks:
#     modules_to_hook:
#       displayHome:
#         - ps_featuredproducts
#         - ps_customtext
